company: 'Gentleman Scholar'
file_shares:
  'jobs':
    root_path: '//scholar/projects'
  'library':
    root_path: '//scholar/assets'
  'tools':
    root_path: '//scholar/pipeline'
  'home':
    root_path: '//scholar/homes'