company: 'Gentleman Scholar'
servers:
  'jobs':
    root_path: '//scholar/projects'
  'assets':
    root_path: '//scholar/assets'
  'personal':
    root_path: '//scholar/homes'
  'footage':
    root_path: '//scholar/footage'
  'apps':
    root_path: '//scholar/apps'
  'pipeline':
    root_path: '//scholar/pipeline'
