company: 'Gentleman Scholar'
servers:
  'jobs':
    root_path: 'c:/projects'
    share_type: 'job_share'
  'assets':
    root_path: 'c:/assets'
    share_type: 'lib_share'
  'personal':
    root_path: 'c:/homes'
    share_type: 'user_share'
  'footage':
    root_path: 'c:/footage'
    share_type: 'media_share'
  'apps':
    root_path: 'c:/apps'
    share_type: 'package_share'
  'pipeline':
    root_path: 'c:/pipeline'
    share_type: 'tools_share'
